---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-backend
  labels:
    app: eshop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-backend
  template:
    metadata:
      labels:
        app: eshop-backend
    spec:
      containers:
      - name: backend
        # You'll need to build and push this image to a registry
        # For now, using a placeholder - we'll need to build from your node/ folde
        image: ghcr.io/glamprinakis/eshop-backend:202508311436
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-backend
  labels:
    app: eshop-backend
spec:
  selector:
    app: eshop-backend
  ports:
  - port: 3000
    targetPort: 3000
    name: http
