---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 1h
  chart:
    spec:
      chart: pihole
      version: 2.26.1
      sourceRef:
        kind: HelmRepository
        name: mojo2600
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: pihole-secret
      valuesKey: admin-password
      targetPath: adminPassword
  values:
    # Pi-hole configuration
    image:
      repository: pihole/pihole
      tag: 2024.07.0

    # DNS configuration
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"

    # Timezone
    timezone: "Europe/Athens"

    # Service configuration
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.31.240"
      annotations:
        io.cilium/lb-ipam-ips: "192.168.31.240"
      mixedService: true

    # Web interface
    serviceWeb:
      type: ClusterIP
      port: 80

    # Ingress for web interface
    ingress:
      enabled: false

    # Persistence - enabled with OpenEBS
    persistentVolumeClaim:
      enabled: true
      storageClass: openebs-hostpath
      accessModes:
        - ReadWriteOnce
      size: 1Gi

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

    # Pod security context
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0

    # Additional environment variables
    extraEnvVars:
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
