---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "8.5.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Image configuration
    image:
      repository: grafana/grafana
      tag: "11.2.0"
      pullPolicy: IfNotPresent

    # Admin credentials
    adminUser: admin
    adminPassword: "${SECRET_GRAFANA_ADMIN_PASSWORD}"

    # Timezone
    defaultDashboardsTimezone: "Europe/Athens"

    # Service configuration (ClusterIP for Gateway routing)
    service:
      type: ClusterIP
      port: 80

    # Ingress disabled (using HTTPRoute instead)
    ingress:
      enabled: false

    persistentVolumeClaim:
      enabled: false

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472

    # Grafana configuration
    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}"
        serve_from_sub_path: false
      security:
        allow_embedding: true
        cookie_secure: true
        strict_transport_security: true
      auth:
        disable_login_form: false
      auth.anonymous:
        enabled: false
      users:
        allow_sign_up: false
        auto_assign_org: true
        auto_assign_org_role: Viewer
      log:
        level: info

    # Default dashboards
    defaultDashboardsEnabled: true

    # Data sources (can be configured later)
    datasources: {}

    # Dashboard providers
    dashboardProviders: {}

    # Sidecar for dashboard discovery
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
