---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.76.6
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: tailscale-secret
      valuesKey: TAILSCALE_CLIENT_ID
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secret
      valuesKey: TAILSCALE_CLIENT_SECRET
      targetPath: oauth.clientSecret
  values:
    # Tailscale operator configuration
    operatorConfig:
      # This allows the operator to manage subnet routes
      defaultTags:
        - tag:k8s
      hostname: "kubernetes-cluster"
