# Tailscale OAuth credentials
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
type: Opaque
stringData:
    TAILSCALE_CLIENT_ID: ENC[AES256_GCM,data:MAKU1KCyiFMM1dU2urEQmGU=,iv:z57n3seqO1ktciDWcHlk/fR/sklGZllalsgF/oed14c=,tag:295umG9+YWs73zOOYr4GWw==,type:str]
    TAILSCALE_CLIENT_SECRET: ENC[AES256_GCM,data:NkWvVziyyHnfXdkB/YvWfGE6ffCjsxozdkpPF9WEYDADlhSSr8OYS6BHlQV5FHgqnY7ONyVewMjlSxcWVuE3,iv:GPuy3hKfcXsxXJxFpyGQHdtehEfyZhnzRA/zc9lPp1g=,tag:XrV2kJ/X85HjF02xnHOWNg==,type:str]
sops:
    age:
        - recipient: age1rfhjffgpnm7tcgcaj4ecq4y8t6j5dp4dcpseuqg66tj707wm49vsjffx8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTXd1S0VTMElqSkp2N05a
            WE8yTTV4dlhZeVFGbnIvMTA3Z3pnaVdTdVJVCnJ0RlhaWDQyOEwrN1N6dC9OOElh
            Y0tIck9FVmZFNHcwQW10S2lHL1k4WWsKLS0tIGtWL0czbjlHSElYSmhaMmN4aGEx
            L2pBNmkzdjJ1cHdTdUhhTExDMFVXVkEK8cBH3L2BR6rP1iwv1kcobKXI3Vk3fJ3K
            /iRNXunyg69BqwWRvoisOKhCo8510SdcFvxAA+TulZEwbSRoffG8zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T20:07:28Z"
    mac: ENC[AES256_GCM,data:Adq5f/xNEXrJBsPeHTBHNNdgBT6fumfM5XAo94WDhyVdzqWmA83kGHgYcWP1GW18pCe2IcKFrCxN0VEIJDsH9Nx6qE9eqKtkoWfq0DmgBZ7KA9LC93mQewXwkUz9pnUCe8F8C33Nf261mgGM2QKR5tiTIp5S/lHb6PoFr7CbWfQ=,iv:xImMr1eTRGkv96pBnU4zS3SJr09r8IU2oY0t2aBPyXk=,tag:uINLuyxmWvg32azOLiM3Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
