apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jTctLPYWb/wl11msxzMrwg==,iv:+X2jB9JuxXMNcug30QpWsG13nuZvBcx2iK2SMOETWqg=,tag:RJLTb5w96SJfU/2CAqlIJg==,type:str]
sops:
  age:
    - recipient: age1rfhjffgpnm7tcgcaj4ecq4y8t6j5dp4dcpseuqg66tj707wm49vsjffx8x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdXRGbmt1TVV6cGZMa1Nv
        SGZsaFdad29YMDBvSktHTGVoNkd3eTFkQmdBCkY1U3hXU2wyQituM3JyY1NHbm83
        L0VTanZZS2FxZWhxM3BKbjdEL2dIcTAKLS0tICtTNzI3SkZCQ0tCL3BvYnUyRnJC
        MVFUUU5UNDVmKyt6YTJYRmd6SkxCbmcKNwDaR/V/FwRaDpul+ofCoyPvyQnL2YAS
        ceBXizxV5ncwJkJW760ChNwIDmmVe8k4lOK0HNLqSKvUGIrwBtEf4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-29T18:35:36Z"
  mac: ENC[AES256_GCM,data:ymqlmeYG0N8C0AZsd6lwxSNiltbB0l0bOMSbLOqBO1wu48zApGdTu3+5+rpxtShwAAffH80a3uR7VdDZ9QHYAwLpa7ovJlWwbRGTJxRX+Los10yiani9tDC0IdDhC4gyZvz1PU4rxoBO6lrJSY/4uYIWFSR/i5/gnEZSUBQRmAw=,iv:/KKwrbk+KkLPTp35rCzAL/kLu9t65bV/GP2tp3Yx+VI=,tag:vVonOXjxxS2jnDjLb8BAHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
