---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.2.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: nextcloud-secret
      valuesKey: admin-password
      targetPath: nextcloud.password
  values:
    image:
      repository: nextcloud
      tag: 30.0.2-apache

    nextcloud:
      host: nextcloud.${SECRET_DOMAIN}
      username: admin

      # PHP configuration
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
        www.conf: |
          [www]
          pm = dynamic
          pm.max_children = 120
          pm.start_servers = 12
          pm.min_spare_servers = 6
          pm.max_spare_servers = 18

    # Internal database (for simplicity)
    internalDatabase:
      enabled: true
      name: nextcloud

    # Disable external database
    externalDatabase:
      enabled: false

    # Persistence
    persistence:
      enabled: true
      storageClass: openebs-hostpath
      accessMode: ReadWriteOnce
      size: 50Gi

    # Service
    service:
      type: ClusterIP
      port: 8080

    # Ingress disabled - using Gateway API HTTPRoute
    ingress:
      enabled: false

    # Resources
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 2Gi

    # Cronjob for background tasks
    cronjob:
      enabled: true
      schedule: "*/5 * * * *"
