apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:5FQB0vphHwn6veJ/zxY4/uU/,iv:53bULxoOYoWZSbsZG8RGariveiutFWf8RGNtnDMn9HQ=,tag:Xuz0eGa0QUkRmB3llh/OUA==,type:str]
sops:
  age:
    - recipient: age1rfhjffgpnm7tcgcaj4ecq4y8t6j5dp4dcpseuqg66tj707wm49vsjffx8x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweWx3SU42U0kyTFdSSW4x
        aUZBSlNvcFJvUTVoRnVHWU56dUdTZk15alFBClhUQ3VRQVM5RlkvUUtnMnpOOHlV
        UTlnY0Z1SWd1d2RiVGNYVy9YUVdXSWsKLS0tIDloN2lBc1g5MTVXQ0srdldaTUV4
        eTF0eCs3UXVjaE1ndGtzZmtrT1Jud0UKnz5NZKeqlD4Q0jXdZjDny+uhAunpWb+A
        ORQM8Ikg/Nddn9HtCWkUHqzG585is6H8JN1Bppa5TbQLratSaF+6CQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-15T19:35:27Z"
  mac: ENC[AES256_GCM,data:Ag4ISQDo8FUWwayJxX2KMtCI70KJeigMrMhBOFRbfPLeA+NpgjTUj0STdxEtKBtGSQ/TNsz8h1iZYqhydpTj2RU5x1IzQDfs2GpyHwL5oI1854bf+39P2WIxyZ9Oq+q495SzSmDk3gh0Q4Khv2X3n2Kcwm0PHkQ6DM1ZjKAvOVk=,iv:4KMMJYv0vQe6oWZcvNQouGuWDQLILE3jxuGnbVuPGgs=,tag:rat4l7kHDLuNUlEnTPbz7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
